### ISSUE TITLE
Watchface bundle should not require icons

### ISSUE THREAD

**Issue by mattrossman** [Willow-Systems/psuedo-dev-portal#2]
The [publishing guidelines](https://developer.rebble.io/developer.pebble.com/guides/appstore-publishing/publishing-an-app/index.html#listing-resources) do not require icons for watchfaces since they are not displayed on the store.

Currently the pseudo dev portal requires you to bundle icons with watchfaces.

**Comment by Willow-Systems** [comment]
@mattrossman Thanks for reporting! Watchfaces no longer require icons. Fixed & deployed to production
